# Generated by Django 3.0.8 on 2021-01-20 11:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=100)),
                ('current_credits', models.IntegerField()),
                ('mail_id', models.EmailField(default=False, max_length=254)),
                ('Phone_num', phonenumber_field.modelfields.PhoneNumberField(default=False, max_length=128, region=None)),
            ],
        ),
    ]
