# Generated by Django 3.0.8 on 2021-01-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Phone_num',
            field=models.IntegerField(max_length=10),
        ),
    ]
