# Generated by Django 3.0.8 on 2021-01-21 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0002_auto_20210120_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Of_Sender', models.CharField(max_length=50)),
                ('Name_Of_Receiver', models.CharField(max_length=50)),
                ('Transfer_Amount', models.IntegerField()),
                ('Sender_Updated_Balance', models.IntegerField()),
                ('Receiver_Updated_Balance', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='Phone_num',
            field=models.IntegerField(),
        ),
    ]
